site_name: DbMover/PgSQL
site_url: http://dbmover.monomelodies.nl/pgsql/docs/
repo_url: https://github.com/dbmover/pgsql

pages:
- Home:
    - 'General documentation': 'index.md'
- Plugins:
    - 'Conditionals': 'conditionals.md'
    - 'Indexes and constraints': 'indexes-and-constraints.md'
    - 'Procedures': 'procedures.md'
    - 'Sequences': 'sequences.md'
    - 'Tables': 'tables.md'
    - 'Triggers': 'triggers.md'
    - 'Views': 'views.md'
